let Cards_json : Array<any> = [
  {
    "type": "cities",
    "name": "Vire",
    "rent" : [2, 4, 10, 30, 90, 160, 250],
    "buildCost": 50,
    "mortgage": 30,
    "cost": 60,
    "bg": "",
    "fg": "",
    "color": "brown",
    "pos": 1
  },
  {
    "type": "cities",
    "name": "Le-Mont-Saint-Michel",
    "rent" : [4, 8, 20, 60, 180, 360, 450],
    "buildCost": 50,
    "mortgage": 30,
    "cost": 60,
    "bg": "",
    "fg": "",
    "color": "brown",
    "pos": 3
  },
  {
    "type": "cities",
    "name": "Alençon",
    "rent" : [6, 12, 30, 90, 270, 400, 550],
    "buildCost": 50,
    "mortgage": 50,
    "cost": 100,
    "bg": "",
    "fg": "",
    "color": "light blue",
    "pos": 6
  },
  {
    "type": "cities",
    "name": "Villedieu-Les-Poêles",
    "rent" : [6, 12, 30, 90, 270, 400, 550],
    "buildCost": 50,
    "mortgage": 30,
    "cost": 60,
    "bg": "",
    "fg": "",
    "color": "light blue",
    "pos": 8
  },
  {
    "type": "cities",
    "name": "Bernay",
    "rent" : [8, 16, 40, 100, 300, 450, 600],
    "buildCost": 50,
    "mortgage": 60,
    "cost": 120,
    "bg": "",
    "fg": "",
    "color": "light blue",
    "pos": 9
  },
  {
    "type": "cities",
    "name": "Pointe du Hoc",
    "rent" : [10, 20, 50, 150, 450, 625, 750],
    "buildCost": 100,
    "mortgage": 70,
    "cost": 140,
    "bg": "",
    "fg": "",
    "color": "scarlet",
    "pos": 11
  },
  {
    "type": "cities",
    "name": "Fécamp",
    "rent" : [10, 20, 50, 150, 450, 625, 750],
    "buildCost": 100,
    "mortgage": 70,
    "cost": 140,
    "bg": "",
    "fg": "",
    "color": "scarlet",
    "pos": 13
  },
  {
    "type": "cities",
    "name": "Lisieux",
    "rent" : [12, 24, 60, 180, 500, 700, 900],
    "buildCost": 100,
    "mortgage": 80,
    "cost": 160,
    "bg": "",
    "fg": "",
    "color": "scarlet",
    "pos": 14
  },
  {
    "type": "cities",
    "name": "Le Bec-Hellouin",
    "rent" : [14, 28, 70, 200, 550, 750, 950],
    "buildCost": 100,
    "mortgage": 90,
    "cost": 180,
    "bg": "",
    "fg": "",
    "color": "orange",
    "pos": 16
  },
  {
    "type": "cities",
    "name": "Forges-Les-Eaux",
    "rent" : [14, 28, 70, 200, 550, 750, 950],
    "buildCost": 100,
    "mortgage": 90,
    "cost": 180,
    "bg": "",
    "fg": "",
    "color": "orange",
    "pos": 18
  },
  {
    "type": "cities",
    "name": "Villequier",
    "rent" : [16, 32, 80, 220, 600, 800, 1000],
    "buildCost": 100,
    "mortgage": 100,
    "cost": 200,
    "bg": "",
    "fg": "",
    "color": "orange",
    "pos": 19
  },
  {
    "type": "cities",
    "name": "Lyons-La-Forêt",
    "rent" : [18, 36, 90, 250, 700, 875, 1050],
    "buildCost": 150,
    "mortgage": 100,
    "cost": 220,
    "bg": "",
    "fg": "",
    "color": "red",
    "pos": 21
  },
  {
    "type": "cities",
    "name": "Le Havre",
    "rent" : [18, 36, 90, 250, 700, 875, 1050],
    "buildCost": 150,
    "mortgage": 100,
    "cost": 220,
    "bg": "",
    "fg": "",
    "color": "red",
    "pos": 23
  },
  {
    "type": "cities",
    "name": "Dieppe",
    "rent" : [20, 40, 100, 300, 750, 925, 1100],
    "buildCost": 150,
    "mortgage": 120,
    "cost": 220,
    "bg": "",
    "fg": "",
    "color": "red",
    "pos": 24
  },
  {
    "type": "cities",
    "name": "Bayeux",
    "rent" : [22, 44, 110, 330, 800, 975, 1150],
    "buildCost": 150,
    "mortgage": 130,
    "cost": 260,
    "bg": "",
    "fg": "",
    "color": "yellow",
    "pos": 26
  },
  {
    "type": "cities",
    "name": "Gisors",
    "rent" : [22, 44, 110, 330, 800, 975, 1150],
    "buildCost": 150,
    "mortgage": 130,
    "cost": 260,
    "bg": "",
    "fg": "",
    "color": "yellow",
    "pos": 27
  },
  {
    "type": "cities",
    "name": "Giverny",
    "rent" : [24, 48, 120, 360, 850, 1025, 1200],
    "buildCost": 150,
    "mortgage": 140,
    "cost": 280,
    "bg": "",
    "fg": "",
    "color": "yellow",
    "pos": 29
  },
  {
    "type": "cities",
    "name": "Îles Chausey",
    "rent" : [26, 52, 130, 390, 900, 1100, 1275],
    "buildCost": 200,
    "mortgage": 150,
    "cost": 300,
    "bg": "",
    "fg": "",
    "color": "lime",
    "pos": 31
  },
  {
    "type": "cities",
    "name": "Etretat",
    "rent" : [26, 52, 130, 390, 900, 1100, 1275],
    "buildCost": 200,
    "mortgage": 150,
    "cost": 300,
    "bg": "",
    "fg": "",
    "color": "lime",
    "pos": 32
  },
  {
    "type": "cities",
    "name": "Honfleur",
    "rent" : [28, 56, 150, 450, 1000, 1200, 1400],
    "buildCost": 200,
    "mortgage": 160,
    "cost": 320,
    "bg": "",
    "fg": "",
    "color": "lime",
    "pos": 34
  },
  {
    "type": "cities",
    "name": "Cabourg",
    "rent" : [35, 70, 175, 500, 1100, 1300, 1500],
    "buildCost": 200,
    "mortgage": 175,
    "cost": 350,
    "bg": "",
    "fg": "",
    "color": "blue",
    "pos": 37
  },
  {
    "type": "cities",
    "name": "Deauville",
    "rent" : [50, 100, 200, 600, 1400, 1700, 2000],
    "buildCost": 200,
    "mortgage": 200,
    "cost": 400,
    "bg": "",
    "fg": "",
    "color": "blue",
    "pos": 39
  },
  {
    "type": "actions",
    "name": "caisse de communauté",
    "actionType": "cummonauty",
    "description": "Get a commo",
  },
  {
      "type": "actions",
      "name": "caisse de communauté",
      "actionType": "cummunity",
  
      "descriuption": "et a cmmolnauty",
      "bg": "",
      "color": "",
      "fg": "",
      "pos": 2
    },
    {
      "type": "actions",
      "name": "caisse de communauté",
      "actionType": "cummo8nauty",
      "description": "et a cmmonauty",
      "bg": "",
      "color": "",
      "fg": "",
      "pos": 17
    },
    {
      "type": "actions",
      "name": "caisse de communauté",
      "actionType": "cummo8nauty",
      "description": "et a cmmonauty",
      "bg": "",
      "color": "",
      "fg": "",
      "pos": 33
    },
    {
      "type": "actions",
      "name": "luck",
      "actionType": "luck",
      "description": "luck",
      "bg": "",
      "color": "",
      "fg": "",
      "pos": 7
    },
    {
      "type": "actions",
      "name": "luck",
      "actionType": "luck",
      "description": "luck",
      "bg": "",
      "color": "",
      "fg": "",
      "pos": 22
    },
    {
      "type": "actions",
      "name": "luck",
      "actionType": "luck",
      "description": "luck",
      "bg": "",
      "color": "",
      "fg": "",
      "pos": 36
    },
    {
      "type": "actions",
      "name": "taxe",
      "actionType": "taxe",
      "description": "Taxe of luxury",
      "bg": "",
      "color": "",
      "fg": "",
      "pos": 38
    },
    {
      "type": "actions",
      "name": "taxe",
      "actionType": "taxe",
      "description": "income tax",
      "bg": "",
      "color": "",
      "fg": "",
      "pos": 4
    },
    {
      "type": "companies",
      "name": "Gare de Rouen",
      "cost": 200,
      "mortgage": 100,
      "multiplier": [25,50,100,200],
      "bg": "",
      "color": "",
      "fg": "",
      "pos": 5
    },
    {
      "type": "companies",
      "name": "Gare de Caen",
      "cost": 200,
      "mortgage": 100,
      "multiplier": [25,50,100,200],
      "bg": "",
      "color": "",
      "fg": "",
      "pos": 15
    },
    {
      "type": "companies",
      "name": "Gare d'Evreux",
      "cost": 200,
      "mortgage": 100,
      "multiplier": [25,50,100,200],
      "bg": "",
      "color": "",
      "fg": "",
      "pos": 25
    },
    {
      "type": "companies",
      "name": "Gare de Cherbourg",
      "cost": 200,
      "mortgage": 100,
      "multiplier": [25,50,100,200],
      "bg": "",
      "color": "",
      "fg": "",
      "pos": 35
    },
    {
      "type": "companies",
      "name": "Compagnies d'électricité",
      "cost": 150,
      "mortgage": 75,
      "multiplier": [4,10],
      "bg": "",
      "color": "",
      "fg": "",
      "pos": 12
    },,
    {
      "type": "companies",
      "name": "Compagnies de distribution d'eau",
      "cost": 150,
      "mortgage": 75,
      "multiplier": [4,10],
      "bg": "",
      "color": "",
      "fg": "",
      "pos": 28
    },
    {
      "type": "action",
      "name": "start",
      "actionType": "start",
      "description": "start +200",
      "bg": "",
      "color": "",
      "fg": "",
      "pos": 0
    },
    {
      "type": "prison",
      "name": "jail",
      "actionType": "jail",
      "description": "Just pass or go Jail",
      "bg": "",
      "color": "",
      "fg": "",
      "pos": 10
    },
    {
      "type": "action",
      "name": "freePark",
      "actionType": "freePark",
      "description": "get the money back",
      "bg": "",
      "color": "",
      "fg": "",
      "pos": 20
    },
    {
      "type": "action",
      "name": "goto",
      "actionType": "goto",
      "description": "goto jail",
      "bg": "",
      "color": "",
      "fg": "",
      "pos": 30
    }
];

export default{
    Cards_json
}